medical_telegram_dwh: # This is the profile name, which you'll reference in dbt_project.yml
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}" # Cast port to integer
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public # This is the default schema where dbt will look for your raw tables and create models if not specified otherwise
      threads: 4 # Number of concurrent queries dbt can run