# medical_telegram_dwh/dbt_project.yml
name: 'medical_telegram_dwh'
version: '1.0.0'
config-version: 2

profile: 'medical_telegram_dwh' # <--- This must match the profile name in ~/.dbt/profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to clean `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"

# Configure models
models:
  medical_telegram_dwh:
    # This sets the default materialization for all models in the project
    # to 'view'. You can override this for specific models or sub-directories.
    +materialized: view

    # Define schema and materialization configurations for different layers
    staging:
      +schema: staging # Staging models will be created in the 'staging' schema
      +materialized: view # Staging models often use views for quick iteration and minimal storage
    marts:
      +schema: marts # Mart models will be created in the 'marts' schema
      +materialized: table # Marts are typically tables for performance and querying by BI tools