# medical_telegram_dwh/models/sources.yml
version: 2

sources:
  - name: public_staging # This is the schema name in your database
    database: telegram_medical # Your database name
    schema: public_staging # Explicitly define the schema name here
    tables:
      - name: image_detections_staging
        description: "Staging table for raw object detection results from images."
        columns:
          - name: message_id
            description: "Foreign key to the message in fct_messages."
          - name: image_path
            description: "Path to the image file."
          - name: detected_object_class
            description: "Class of the object detected (e.g., 'person', 'car')."
          - name: confidence_score
            description: "Confidence score of the detection."
          - name: detection_timestamp
            description: "Timestamp when the object detection was performed